databases:
  - name: fb_login
    plan: free
    databaseName: fb_login
    user: fb_login


services:
  - type: web
    plan: free
    name: fb_login
    runtime: python
    buildCommand: "./build.sh"  # Adjust this if you have a build script
    startCommand: "uvicorn fasthands.asgi:application --host 0.0.0.0 --port $PORT --workers 4"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: 'False'
      - key: PORT
        value: '8000'
      - key: DATABASE_URL
        fromDatabase:
          name: fb_login
          property: connectionString
      - key: CREATE_SUPERUSER
        value: 'True'
      - key: DJANGO_SUPERUSER_EMAIL
        value: 'kalilinux@gmail.com'
      - key: DJANGO_SUPERUSER_PASSWORD
        value: 'kalilinux'
      - key: DJANGO_SUPERUSER_USERNAME
        value: 'kalilinux'